/* Project Executive Center (Gate 9) — a management-facing rollup of every register PCC
 * already has, per project. Consolidates, never duplicates: every number here is
 * computed from data.projects/activities/risks/rfis/change_orders/meetings/cost_* at
 * render time, the same store everything else in this app reads. Nothing is cached or
 * snapshotted, so the page always reflects the data as of the moment it's opened —
 * same "reports read live from the store" rule reports.js already documents.
 *
 * SCOPE, DELIBERATELY:
 * - EVM tiles/charts only render when the project actually has Cost Tracking budget
 *   items (Gate 7's EVM engine needs them to mean anything) — no fabricated PV/EV/CPI.
 * - Resource Management KPIs are entirely absent — that module doesn't exist yet
 *   (next up per the locked Tier 2 build order). Nothing here should be read as a
 *   placeholder for it; it's just not shown.
 * - Cost KPIs are Budget/Actual/Variance only (what Cost Tracking + Portfolio's Budget
 *   fallback actually track) plus EAC when EVM is available — "Commitments" and "Cash
 *   Flow" have no underlying data model anywhere in PCC yet and are called out as such
 *   rather than shown as a permanent, silently-empty tile.
 * - Activity-level linking to Risks/Issues/RFIs/Meetings/Documents/Vendors/Change
 *   Orders (spec section "Project Control Linking") is NOT built — none of those
 *   registers carry an activity_id, and retrofitting one onto five+ modules is a
 *   schema change on its own scale, deferred to a later phase rather than bolted on
 *   here. Recent Activity / Management Actions / Executive Summary below link to
 *   PROJECT-level records (a risk, an RFI, a meeting), not to a specific activity.
 * - Charts a project has no data for say so ("No data available") rather than
 *   rendering a misleadingly empty axis.
 * - The Health Score is a plain, documented formula (see projectHealthEngine.js) with
 *   configurable weights and a visible per-factor breakdown — not a black box, and
 *   not AI.
 * - Executive Summary is template/data-driven text the user can edit and save — never
 *   generated by a model. See newExecutiveSummary() in store.js.
 */
(function () {
  "use strict";
  window.PCC = window.PCC || {};
  window.PCC.pages = window.PCC.pages || {};

  var SEVERITY_MATRIX = {
    high: { low: "medium", medium: "high", high: "high" },
    medium: { low: "low", medium: "medium", high: "high" },
    low: { low: "low", medium: "low", high: "medium" },
  };
  var RISK_LEVELS = ["low", "medium", "high"];

  var uiState = {
    projectId: "",
    tab: "overview", // 'overview' | 'output'
    editingSummarySection: null, // 'status' | 'achievements' | 'challenges' | 'attention' | 'upcoming' | null
    editingWeights: false,
    upcomingRangeDays: 30,
    outputMode: "snapshot", // 'snapshot' | 'pack'
    packSections: {
      cover: true, summary: true, snapshot: true, kpis: true, progress: true,
      schedule: true, milestones: true, cost: true, evm: true, risks: true,
      issues: true, rfis: true, changes: true, dailylog: true, meetings: true,
    },
  };

  function esc(s) {
    var div = document.createElement("div");
    div.textContent = s === null || s === undefined ? "" : String(s);
    return div.innerHTML;
  }

  function today() {
    return new Date().toISOString().slice(0, 10);
  }

  function fmtMoney(amount, currency) {
    if (amount === null || amount === undefined || amount === "" || isNaN(Number(amount))) return "—";
    var n = Number(amount);
    return (currency ? currency + " " : "") + n.toLocaleString(undefined, { maximumFractionDigits: 2 });
  }

  function fmtPct(n) {
    if (n === null || n === undefined || isNaN(n)) return "—";
    return Math.round(n) + "%";
  }

  function riskSeverity(r) {
    return SEVERITY_MATRIX[r.probability] ? SEVERITY_MATRIX[r.probability][r.impact] : "medium";
  }

  // ---------------------------------------------------------------------------------
  // Context gathering — every number the rest of this page needs, in one place, so
  // KPIs/health/diagnostics/summary/charts/snapshot all read from the same computed
  // values instead of five slightly-different re-derivations of "what's overdue."
  // ---------------------------------------------------------------------------------

  function pickPrimarySchedule(schedules) {
    if (schedules.length === 0) return null;
    var active = schedules.filter(function (s) { return s.status === "active"; });
    var pool = active.length ? active : schedules;
    return pool.slice().sort(function (a, b) {
      if (a.revision_number !== b.revision_number) return b.revision_number - a.revision_number;
      return new Date(b.updated_at) - new Date(a.updated_at);
    })[0];
  }

  function buildProjectContext(data, projectId) {
    var project = data.projects.find(function (p) { return p.id === projectId; });
    var todayIso = today();
    var ctx = { project: project, todayIso: todayIso };
    if (!project) return ctx;

    // ---- Schedule ----
    var projectSchedules = data.schedules.filter(function (s) { return s.project_id === projectId; });
    var schedule = pickPrimarySchedule(projectSchedules);
    ctx.schedule = schedule;
    ctx.scheduleCount = projectSchedules.length;

    var activities = schedule ? data.activities.filter(function (a) { return a.schedule_id === schedule.id; }) : [];
    var relationships = schedule ? data.relationships.filter(function (r) { return r.schedule_id === schedule.id; }) : [];
    ctx.activities = activities;
    ctx.relationships = relationships;

    var cpm = null;
    if (schedule && activities.length > 0) {
      cpm = window.PCC.scheduleCpmEngine.calculateSchedule(activities, relationships, {
        dataDate: schedule.data_date,
        nearCriticalThresholdDays: schedule.near_critical_threshold_days,
      });
    }
    ctx.cpm = cpm;

    var referenceDate = (schedule && schedule.data_date) || todayIso;
    ctx.referenceDate = referenceDate;

    var criticalActivities = [];
    var nearCriticalActivities = [];
    var delayedActivities = [];
    var completedCount = 0;
    var plannedDates = [];
    var weightedProgressNumerator = 0;
    var weightedProgressDenominator = 0;
    var weightedPhysicalNumerator = 0;

    activities.forEach(function (a) {
      var r = cpm && cpm.results[a.id];
      var totalFloat = r ? r.total_float : a.total_float;
      var earlyFinish = r ? r.early_finish : a.early_finish;
      var effectiveFinish = earlyFinish || a.planned_finish;

      if (totalFloat != null && totalFloat <= 0) criticalActivities.push({ id: a.id, name: a.name });
      else if (totalFloat != null && totalFloat > 0 && totalFloat <= (schedule ? schedule.near_critical_threshold_days : 5)) {
        nearCriticalActivities.push({ id: a.id, name: a.name });
      }
      if (effectiveFinish && effectiveFinish < referenceDate && a.status !== "complete") {
        delayedActivities.push({ id: a.id, name: a.name, finish: effectiveFinish });
      }
      if (a.status === "complete") completedCount++;
      if (a.planned_start) plannedDates.push(a.planned_start);
      if (a.planned_finish) plannedDates.push(a.planned_finish);

      var weight = a.duration != null && a.duration > 0 ? a.duration : 1;
      weightedProgressNumerator += weight * (Number(a.percent_complete) || 0);
      weightedProgressDenominator += weight;
      weightedPhysicalNumerator += weight * (Number(a.physical_progress) || 0);
    });

    ctx.totalActivityCount = activities.length;
    ctx.criticalActivities = criticalActivities;
    ctx.nearCriticalActivities = nearCriticalActivities;
    ctx.delayedActivities = delayedActivities;
    ctx.completedActivityCount = completedCount;
    ctx.scheduleProgressPct = weightedProgressDenominator > 0 ? (weightedProgressNumerator / weightedProgressDenominator) : null;
    ctx.physicalProgressPct = weightedProgressDenominator > 0 ? (weightedPhysicalNumerator / weightedProgressDenominator) : null;
    ctx.plannedStart = plannedDates.length ? plannedDates.reduce(function (a, b) { return a < b ? a : b; }) : (project.start_date || null);
    ctx.plannedFinish = plannedDates.length ? plannedDates.reduce(function (a, b) { return a > b ? a : b; }) : (project.finish_date || null);
    ctx.plannedDurationDays =
      ctx.plannedStart && ctx.plannedFinish ? window.PCC.scheduleGanttLayout.diffDays(ctx.plannedStart, ctx.plannedFinish) : null;
    ctx.forecastFinish = cpm && cpm.projectFinish ? cpm.projectFinish : (project.forecast_finish_date || null);
    ctx.forecastFinishSource = cpm && cpm.projectFinish ? "calculated" : (project.forecast_finish_date ? "manual" : "none");
    ctx.forecastVarianceDays = cpm ? cpm.forecastVarianceDays : null;

    // Milestones
    var milestoneActivities = activities.filter(function (a) { return a.activity_type === "milestone"; });
    var upcomingMilestones = [];
    var slippedMilestones = [];
    milestoneActivities.forEach(function (a) {
      var r = cpm && cpm.results[a.id];
      var calcDate = r ? r.early_start : a.early_start;
      var effDate = calcDate || a.planned_start;
      if (effDate && effDate >= todayIso) upcomingMilestones.push({ id: a.id, name: a.name, date: effDate });
      if (calcDate && a.planned_start && calcDate > a.planned_start) {
        slippedMilestones.push({
          id: a.id,
          name: a.name,
          varianceDays: window.PCC.scheduleGanttLayout.diffDays(a.planned_start, calcDate),
        });
      }
    });
    upcomingMilestones.sort(function (a, b) { return a.date < b.date ? -1 : 1; });
    ctx.upcomingMilestones = upcomingMilestones;
    ctx.slippedMilestones = slippedMilestones;

    // ---- Cost ----
    var costSummary = window.PCC.cost ? window.PCC.cost.projectCostSummary(data, projectId) : { budgeted: 0, actual: 0, variance: 0, usingPortfolioBudget: false };
    ctx.costSummary = costSummary;
    var budgetItems = data.cost_budget_items.filter(function (b) { return b.project_id === projectId; });
    var actuals = data.cost_actuals.filter(function (a) { return a.project_id === projectId; });
    ctx.budgetItemCount = budgetItems.length;
    ctx.evm =
      budgetItems.length > 0
        ? window.PCC.costEvmEngine.computeEvm(budgetItems, actuals, activities, schedule ? [schedule] : [], {
            bac: costSummary.budgeted,
            ac: costSummary.actual,
          })
        : null;

    // ---- Risks / Issues / Opportunities ----
    var projectRisks = data.risks.filter(function (r) { return r.project_id === projectId; });
    var openRisks = projectRisks.filter(function (r) { return r.status !== "closed" && r.type === "risk"; });
    var openIssues = projectRisks.filter(function (r) { return r.status !== "closed" && r.type === "issue"; });
    var openOpportunities = projectRisks.filter(function (r) { return r.status !== "closed" && r.type === "opportunity"; });
    ctx.allRisks = projectRisks;
    ctx.openRisks = openRisks;
    ctx.openIssues = openIssues;
    ctx.openOpportunities = openOpportunities;
    ctx.highRisks = openRisks.filter(function (r) { return riskSeverity(r) === "high"; });
    ctx.criticalIssues = openIssues.filter(function (r) { return riskSeverity(r) === "high"; });

    // ---- RFI / TQ ----
    var projectRfis = data.rfis.filter(function (r) { return r.project_id === projectId; });
    var openRfis = projectRfis.filter(function (r) { return r.status !== "closed"; });
    var overdueRfis = projectRfis
      .filter(function (r) { return r.status === "open" && r.date_required && r.date_required < todayIso; })
      .map(function (r) {
        return {
          id: r.id, number: r.number, subject: r.subject,
          daysOverdue: window.PCC.scheduleGanttLayout.diffDays(r.date_required, todayIso),
        };
      });
    var answeredRfis = projectRfis.filter(function (r) { return r.date_answered && r.date_raised; });
    var avgResponseDays =
      answeredRfis.length > 0
        ? answeredRfis.reduce(function (sum, r) { return sum + window.PCC.scheduleGanttLayout.diffDays(r.date_raised, r.date_answered); }, 0) / answeredRfis.length
        : null;
    ctx.allRfis = projectRfis;
    ctx.openRfis = openRfis;
    ctx.overdueRfis = overdueRfis;
    ctx.avgRfiResponseDays = avgResponseDays;

    // ---- Change Orders ----
    var projectChangeOrders = data.change_orders.filter(function (co) { return co.project_id === projectId; });
    var pendingChangeOrders = projectChangeOrders.filter(function (co) { return co.status === "pending"; });
    ctx.allChangeOrders = projectChangeOrders;
    ctx.openChangeOrders = projectChangeOrders.filter(function (co) { return co.status === "pending" || co.status === "approved"; });
    ctx.pendingChangeOrders = pendingChangeOrders;
    ctx.approvedChangeOrders = projectChangeOrders.filter(function (co) { return co.status === "approved"; });
    ctx.rejectedChangeOrders = projectChangeOrders.filter(function (co) { return co.status === "rejected"; });

    // ---- Meetings / overdue actions ----
    var projectMeetings = data.meetings.filter(function (m) { return m.project_id === projectId; });
    var overdueMeetingActions = [];
    projectMeetings.forEach(function (m) {
      (m.actions || []).forEach(function (a) {
        if (a.status === "open" && a.due_date && a.due_date < todayIso) {
          overdueMeetingActions.push({ meetingId: m.id, meetingTitle: m.title || "(untitled)", description: a.description, dueDate: a.due_date });
        }
      });
    });
    ctx.meetings = projectMeetings;
    ctx.overdueMeetingActions = overdueMeetingActions;
    var upcomingMeetings = projectMeetings.filter(function (m) { return m.meeting_date && m.meeting_date >= todayIso; }).sort(function (a, b) { return a.meeting_date < b.meeting_date ? -1 : 1; });
    ctx.upcomingMeetings = upcomingMeetings;

    // ---- Documents / Daily Log (for recent activity + snapshot only) ----
    ctx.documents = data.documents.filter(function (d) { return d.project_id === projectId; });
    ctx.dailyLogs = data.daily_logs.filter(function (l) { return l.project_id === projectId; });

    // ---- Resources (Gate 11) — only meaningful once the module has real data; the
    // KPI section itself is gated on data.resources.length > 0, matching the same
    // "only display when the module exists and has data" rule EVM already follows. ----
    // Deliberately every activity across every one of this project's schedule
    // revisions, not just the primary schedule picked above for CPM/KPI purposes — a
    // resource assignment against an older revision's activity still counts.
    var allProjectActivityIds = {};
    data.activities.forEach(function (a) { if (a.project_id === projectId) allProjectActivityIds[a.id] = true; });
    var projectAssignments = data.resource_assignments.filter(function (a) { return allProjectActivityIds[a.activity_id]; });
    var assignedResourceIds = {};
    projectAssignments.forEach(function (a) { assignedResourceIds[a.resource_id] = true; });
    var portfolioOverAlloc = window.PCC.resourceLevelingEngine
      ? window.PCC.resourceLevelingEngine.portfolioOverAllocationSummary(data.resources, data.resource_assignments, data.activities)
      : [];
    var overAllocById = {};
    portfolioOverAlloc.forEach(function (s) { overAllocById[s.resourceId] = s; });
    ctx.assignedResourceCount = Object.keys(assignedResourceIds).length;
    ctx.overAllocatedResources = Object.keys(assignedResourceIds)
      .filter(function (id) { return overAllocById[id]; })
      .map(function (id) { return overAllocById[id]; });

    // ---- Document Control (Gate 27: Executive Summary section only — same computed
    // Available/Overdue/Required status every Document Control gate since Gate 18 has
    // used, duplicated here per this app's per-module-helpers convention). ----
    var docTypesById = {};
    data.document_types.forEach(function (t) { docTypesById[t.id] = t; });
    var projectDocRequirements = data.project_document_requirements.filter(function (r) {
      return r.project_id === projectId && docTypesById[r.document_type_id];
    });
    var docControlAvailable = 0;
    var docControlOverdue = 0;
    var docControlOverdueTypeNames = [];
    projectDocRequirements.forEach(function (r) {
      var available = data.documents.some(function (d) { return d.project_id === projectId && d.document_type_id === r.document_type_id; });
      if (available) {
        docControlAvailable++;
      } else if (r.planned_submission_date && r.planned_submission_date < todayIso) {
        docControlOverdue++;
        docControlOverdueTypeNames.push(docTypesById[r.document_type_id].name);
      }
    });
    ctx.docControlTotal = projectDocRequirements.length;
    ctx.docControlAvailable = docControlAvailable;
    ctx.docControlOverdue = docControlOverdue;
    ctx.docControlOverdueTypeNames = docControlOverdueTypeNames;

    return ctx;
  }

  /** Flattens a context into the plain shape projectHealthEngine.js expects. */
  function healthContextFrom(ctx) {
    return {
      totalActivityCount: ctx.totalActivityCount,
      criticalCount: ctx.criticalActivities ? ctx.criticalActivities.length : 0,
      nearCriticalCount: ctx.nearCriticalActivities ? ctx.nearCriticalActivities.length : 0,
      forecastVarianceDays: ctx.forecastVarianceDays,
      plannedDurationDays: ctx.plannedDurationDays,
      budgetTotal: ctx.costSummary ? ctx.costSummary.budgeted : null,
      actualTotal: ctx.costSummary ? ctx.costSummary.actual : null,
      highRiskCount: ctx.highRisks ? ctx.highRisks.length : 0,
      openRiskCount: ctx.openRisks ? ctx.openRisks.length : 0,
      criticalIssueCount: ctx.criticalIssues ? ctx.criticalIssues.length : 0,
      openIssueCount: ctx.openIssues ? ctx.openIssues.length : 0,
      overdueRfiCount: ctx.overdueRfis ? ctx.overdueRfis.length : 0,
      openRfiCount: ctx.openRfis ? ctx.openRfis.length : 0,
      pendingChangeOrderCount: ctx.pendingChangeOrders ? ctx.pendingChangeOrders.length : 0,
    };
  }

  function diagnosticsContextFrom(ctx) {
    return {
      spi: ctx.evm ? ctx.evm.spi : null,
      cpi: ctx.evm ? ctx.evm.cpi : null,
      bac: ctx.evm ? ctx.evm.bac : null,
      eac: ctx.evm ? ctx.evm.eac : null,
      budgetTotal: ctx.costSummary ? ctx.costSummary.budgeted : null,
      actualTotal: ctx.costSummary ? ctx.costSummary.actual : null,
      criticalActivities: ctx.criticalActivities,
      nearCriticalActivities: ctx.nearCriticalActivities,
      slippedMilestones: ctx.slippedMilestones,
      highRisks: ctx.highRisks ? ctx.highRisks.map(function (r) { return { id: r.id, title: r.title }; }) : [],
      overdueRfis: ctx.overdueRfis,
      overdueMeetingActions: ctx.overdueMeetingActions,
      pendingChangeOrders: ctx.pendingChangeOrders ? ctx.pendingChangeOrders.map(function (co) { return { id: co.id, number: co.number, title: co.title }; }) : [],
    };
  }

  // ---------------------------------------------------------------------------------
  // SVG chart helpers — plain SVG, no charting library, matching the Gantt's own
  // approach (scheduleGanttLayout.js + schedule.js). Each returns a DOM node; callers
  // append it. Every chart shows "No data available" instead of a misleadingly empty
  // axis when its inputs are empty.
  // ---------------------------------------------------------------------------------

  var SVG_NS = "http://www.w3.org/2000/svg";
  function svgEl(tag, attrs) {
    var el = document.createElementNS(SVG_NS, tag);
    if (attrs) Object.keys(attrs).forEach(function (k) { el.setAttribute(k, attrs[k]); });
    return el;
  }

  function chartCard(title) {
    var card = document.createElement("div");
    card.className = "panel";
    card.style.flex = "1 1 320px";
    card.style.minWidth = "280px";
    var h = document.createElement("h4");
    h.style.marginBottom = "10px";
    h.textContent = title;
    card.appendChild(h);
    return card;
  }

  function noDataNote(card, text) {
    var p = document.createElement("p");
    p.className = "text-secondary";
    p.style.fontSize = "13px";
    p.textContent = text || "No data available.";
    card.appendChild(p);
  }

  /** Horizontal bar chart — [{label, value, color}]. Used for Critical vs Non-Critical,
   * Float Distribution, RFI Open vs Closed/Overdue, Change Order status breakdown. */
  function horizontalBarChart(card, items, opts) {
    opts = opts || {};
    var nonZero = items.filter(function (i) { return i.value > 0; });
    if (nonZero.length === 0) return noDataNote(card);
    var maxVal = Math.max.apply(null, items.map(function (i) { return i.value; }));
    var rowH = 26;
    var labelW = opts.labelWidth || 130;
    var chartW = 260;
    var height = items.length * rowH + 6;
    var svg = svgEl("svg", { width: labelW + chartW + 40, height: height, style: "display:block;max-width:100%;" });
    items.forEach(function (item, i) {
      var y = i * rowH;
      var label = svgEl("text", { x: 0, y: y + rowH / 2 + 4, "font-size": 11, fill: "var(--text-primary)" });
      label.textContent = item.label;
      svg.appendChild(label);
      var barMaxW = chartW - 4;
      var w = maxVal > 0 ? (item.value / maxVal) * barMaxW : 0;
      svg.appendChild(
        svgEl("rect", { x: labelW, y: y + 4, width: Math.max(w, item.value > 0 ? 2 : 0), height: rowH - 10, rx: 2, fill: item.color || "var(--status-info)" })
      );
      var valText = svgEl("text", { x: labelW + Math.max(w, 2) + 6, y: y + rowH / 2 + 4, "font-size": 11, fill: "var(--text-secondary)" });
      valText.textContent = String(item.value);
      svg.appendChild(valText);
    });
    card.appendChild(svg);
  }

  /** Simple donut, drawn as stacked arcs via stroke-dasharray on a circle — fine for a
   * handful of segments (this app never needs more than 3-4 in one chart). */
  function donutChart(card, items, opts) {
    opts = opts || {};
    var total = items.reduce(function (s, i) { return s + i.value; }, 0);
    if (total <= 0) return noDataNote(card);
    var size = 140;
    var r = 52;
    var cx = size / 2;
    var cy = size / 2;
    var circumference = 2 * Math.PI * r;
    var svg = svgEl("svg", { width: size, height: size, viewBox: "0 0 " + size + " " + size });
    svg.appendChild(svgEl("circle", { cx: cx, cy: cy, r: r, fill: "none", stroke: "var(--divider)", "stroke-width": 18 }));
    var offset = 0;
    items.forEach(function (item) {
      if (item.value <= 0) return;
      var frac = item.value / total;
      var dash = frac * circumference;
      var circle = svgEl("circle", {
        cx: cx, cy: cy, r: r, fill: "none", stroke: item.color, "stroke-width": 18,
        "stroke-dasharray": dash + " " + (circumference - dash),
        "stroke-dashoffset": -offset,
        transform: "rotate(-90 " + cx + " " + cy + ")",
      });
      svg.appendChild(circle);
      offset += dash;
    });
    var centerText = svgEl("text", { x: cx, y: cy + 5, "font-size": 20, "font-weight": "700", "text-anchor": "middle", fill: "var(--text-primary)" });
    centerText.textContent = total;
    svg.appendChild(centerText);

    var wrap = document.createElement("div");
    wrap.style.display = "flex";
    wrap.style.alignItems = "center";
    wrap.style.gap = "16px";
    wrap.style.flexWrap = "wrap";
    wrap.appendChild(svg);
    var legend = document.createElement("div");
    legend.style.fontSize = "12px";
    items.forEach(function (item) {
      var line = document.createElement("div");
      line.style.display = "flex";
      line.style.alignItems = "center";
      line.style.gap = "6px";
      line.style.marginBottom = "4px";
      var swatch = document.createElement("span");
      swatch.style.width = "10px";
      swatch.style.height = "10px";
      swatch.style.borderRadius = "50%";
      swatch.style.background = item.color;
      swatch.style.display = "inline-block";
      line.appendChild(swatch);
      var text = document.createElement("span");
      text.className = "text-secondary";
      text.textContent = item.label + ": " + item.value;
      line.appendChild(text);
      legend.appendChild(line);
    });
    wrap.appendChild(legend);
    card.appendChild(wrap);
  }

  /** Risk heat map — 3x3 probability x impact grid, counts only (read view; the full
   * interactive/filterable heat map already lives on the Risk Register page). */
  function riskHeatMapMini(card, risks) {
    if (risks.length === 0) return noDataNote(card);
    var levels = RISK_LEVELS;
    var counts = {};
    risks.forEach(function (r) {
      var key = r.probability + ":" + r.impact;
      counts[key] = (counts[key] || 0) + 1;
    });
    var table = document.createElement("table");
    table.style.borderCollapse = "collapse";
    table.style.fontSize = "11px";
    var levelColors = { high: "var(--status-critical)", medium: "var(--status-at-risk)", low: "var(--status-on-track)" };
    for (var pi = levels.length - 1; pi >= 0; pi--) {
      var prob = levels[pi];
      var row = document.createElement("tr");
      var labelCell = document.createElement("td");
      labelCell.textContent = prob.toUpperCase();
      labelCell.className = "text-secondary";
      labelCell.style.padding = "4px 8px";
      row.appendChild(labelCell);
      levels.forEach(function (impact) {
        var sev = SEVERITY_MATRIX[prob][impact];
        var cell = document.createElement("td");
        cell.style.width = "48px";
        cell.style.height = "36px";
        cell.style.textAlign = "center";
        cell.style.border = "1px solid var(--divider)";
        cell.style.background = levelColors[sev];
        cell.style.opacity = "0.25";
        cell.style.position = "relative";
        var count = counts[prob + ":" + impact] || 0;
        var span = document.createElement("div");
        span.style.position = "relative";
        span.style.zIndex = "1";
        span.style.fontWeight = "700";
        span.style.opacity = "1";
        span.style.color = "var(--text-primary)";
        span.textContent = count || "";
        cell.appendChild(span);
        row.appendChild(cell);
      });
      table.appendChild(row);
    }
    var axisRow = document.createElement("tr");
    axisRow.appendChild(document.createElement("td"));
    levels.forEach(function (impact) {
      var td = document.createElement("td");
      td.className = "text-secondary";
      td.style.textAlign = "center";
      td.style.fontSize = "10px";
      td.textContent = impact.toUpperCase();
      axisRow.appendChild(td);
    });
    table.appendChild(axisRow);
    card.appendChild(table);
    var caption = document.createElement("p");
    caption.className = "text-secondary";
    caption.style.fontSize = "11px";
    caption.style.marginTop = "6px";
    caption.textContent = "Rows: Probability · Columns: Impact";
    card.appendChild(caption);
  }

  /** Milestone timeline — a simple horizontal strip of dots, not a full Gantt. */
  function milestoneTimelineMini(card, milestones, todayIso) {
    if (milestones.length === 0) return noDataNote(card, "No upcoming milestones.");
    var sorted = milestones.slice().sort(function (a, b) { return a.date < b.date ? -1 : 1; });
    var minDate = sorted[0].date < todayIso ? sorted[0].date : todayIso;
    var maxDate = sorted[sorted.length - 1].date;
    var totalDays = Math.max(1, window.PCC.scheduleGanttLayout.diffDays(minDate, maxDate));
    var width = 480;
    var height = 60 + sorted.length * 18;
    var svg = svgEl("svg", { width: width, height: height, style: "display:block;max-width:100%;" });
    svg.appendChild(svgEl("line", { x1: 10, y1: 20, x2: width - 10, y2: 20, stroke: "var(--divider)", "stroke-width": 2 }));
    sorted.forEach(function (m, i) {
      var x = 10 + (window.PCC.scheduleGanttLayout.diffDays(minDate, m.date) / totalDays) * (width - 20);
      svg.appendChild(svgEl("circle", { cx: x, cy: 20, r: 5, fill: "var(--signal-amber)" }));
      var label = svgEl("text", { x: x, y: 40 + (i % 3) * 16, "font-size": 10, "text-anchor": "middle", fill: "var(--text-secondary)" });
      label.textContent = m.name.length > 18 ? m.name.slice(0, 17) + "…" : m.name;
      svg.appendChild(label);
      var dateLabel = svgEl("text", { x: x, y: 52 + (i % 3) * 16, "font-size": 9, "text-anchor": "middle", fill: "var(--text-secondary)" });
      dateLabel.textContent = m.date;
      svg.appendChild(dateLabel);
    });
    card.appendChild(svg);
  }

  /** Planned progress S-curve, from real activity dates — a full cumulative-% curve
   * over time. There is no stored "actual progress on date X" history anywhere in PCC
   * (only current percent_complete), so "Actual" can only be plotted as a single point
   * at today/data-date — drawn distinctly and labeled, not a fabricated actual curve. */
  function sCurveChart(card, activities, referenceDate, todayIso) {
    var dated = activities.filter(function (a) { return a.planned_start && a.planned_finish; });
    if (dated.length === 0) return noDataNote(card, "No activities with planned dates yet.");
    var diffDays = window.PCC.scheduleGanttLayout.diffDays;
    var addDays = window.PCC.scheduleGanttLayout.addDays;
    var rangeStart = dated.reduce(function (min, a) { return a.planned_start < min ? a.planned_start : min; }, dated[0].planned_start);
    var rangeEnd = dated.reduce(function (max, a) { return a.planned_finish > max ? a.planned_finish : max; }, dated[0].planned_finish);
    var totalWeight = dated.reduce(function (s, a) { return s + (a.duration || diffDays(a.planned_start, a.planned_finish) || 1); }, 0);
    if (totalWeight <= 0) return noDataNote(card);

    var totalSpan = Math.max(1, diffDays(rangeStart, rangeEnd));
    var steps = Math.min(40, totalSpan);
    var points = [];
    for (var s = 0; s <= steps; s++) {
      var day = addDays(rangeStart, Math.round((s / steps) * totalSpan));
      var cum = 0;
      dated.forEach(function (a) {
        var dur = a.duration || diffDays(a.planned_start, a.planned_finish) || 1;
        var frac;
        if (day <= a.planned_start) frac = 0;
        else if (day >= a.planned_finish) frac = 1;
        else frac = diffDays(a.planned_start, day) / (diffDays(a.planned_start, a.planned_finish) || 1);
        cum += dur * frac;
      });
      points.push({ day: day, pct: (cum / totalWeight) * 100 });
    }

    var width = 480;
    var height = 200;
    var padL = 34;
    var padB = 20;
    var plotW = width - padL - 10;
    var plotH = height - padB - 10;
    function xFor(day) { return padL + (diffDays(rangeStart, day) / totalSpan) * plotW; }
    function yFor(pct) { return 10 + plotH - (pct / 100) * plotH; }

    var svg = svgEl("svg", { width: width, height: height, style: "display:block;max-width:100%;" });
    [0, 25, 50, 75, 100].forEach(function (pct) {
      var y = yFor(pct);
      svg.appendChild(svgEl("line", { x1: padL, y1: y, x2: width - 10, y2: y, stroke: "var(--grid-line)", "stroke-width": 1 }));
      var t = svgEl("text", { x: 2, y: y + 3, "font-size": 9, fill: "var(--text-secondary)" });
      t.textContent = pct + "%";
      svg.appendChild(t);
    });

    var pathD = points.map(function (p, i) { return (i === 0 ? "M " : "L ") + xFor(p.day) + " " + yFor(p.pct); }).join(" ");
    svg.appendChild(svgEl("path", { d: pathD, fill: "none", stroke: "var(--status-info)", "stroke-width": 2 }));

    if (referenceDate >= rangeStart && referenceDate <= rangeEnd) {
      var refX = xFor(referenceDate);
      svg.appendChild(svgEl("line", { x1: refX, y1: 10, x2: refX, y2: 10 + plotH, stroke: "var(--signal-amber)", "stroke-width": 1.5, "stroke-dasharray": "3,3" }));
    }

    card.appendChild(svg);
    var legend = document.createElement("p");
    legend.className = "text-secondary";
    legend.style.fontSize = "11px";
    legend.style.marginTop = "4px";
    legend.textContent = "Planned cumulative progress, duration-weighted across " + dated.length + " dated activity(ies). Dashed line: data date. " +
      "There's no stored day-by-day actual-progress history in PCC to plot a real actual curve — only the current % complete.";
    card.appendChild(legend);
  }

  function floatDistributionBuckets(activities) {
    var buckets = [
      { label: "< 0 (over)", test: function (f) { return f < 0; }, color: "var(--status-critical)" },
      { label: "0 (critical)", test: function (f) { return f === 0; }, color: "var(--status-critical)" },
      { label: "1–5", test: function (f) { return f >= 1 && f <= 5; }, color: "var(--status-at-risk)" },
      { label: "6–15", test: function (f) { return f >= 6 && f <= 15; }, color: "var(--status-info)" },
      { label: "16+", test: function (f) { return f >= 16; }, color: "var(--status-on-track)" },
    ];
    var withFloat = activities.filter(function (a) { return a.total_float != null; });
    return buckets.map(function (b) {
      return { label: b.label, color: b.color, value: withFloat.filter(function (a) { return b.test(a.total_float); }).length };
    });
  }

  window.PCC.pages.executiveCenter = renderPage;
  window.PCC.executiveCenter = {
    viewProject: function (projectId) {
      uiState.projectId = projectId;
      uiState.tab = "overview";
    },
    /** Gate 31 (PCC Evolution Roadmap Gate 3: Management Attention) — the Dashboard's
     * portfolio-wide attention panel needs the same rule-based diagnostics this page's own
     * Diagnostics panel already computes, for every active project, not just whichever one
     * is currently open here. Exposing this one composed function — rather than exporting
     * buildProjectContext() itself, or duplicating its ~220 lines of Schedule/Cost/EVM/
     * Risk/RFI/Meetings/Change gathering into dashboard.js — keeps Dashboard and this page
     * permanently in agreement on what a project's diagnostics are; there's exactly one
     * place this logic lives. */
    getDiagnostics: function (projectId) {
      var data = window.PCC.store.get();
      var ctx = buildProjectContext(data, projectId);
      return window.PCC.projectHealthEngine.computeDiagnostics(diagnosticsContextFrom(ctx));
    },
  };

  function renderPage(outlet) {
    function rerender() {
      outlet.innerHTML = "";
      renderPage(outlet);
    }

    var data = window.PCC.store.get();
    var activeProjects = data.projects.filter(function (p) { return !p.archived; });

    var h1 = document.createElement("h2");
    h1.textContent = "Project Executive Center";
    h1.style.marginBottom = "6px";
    outlet.appendChild(h1);

    var sub = document.createElement("p");
    sub.className = "text-secondary";
    sub.style.fontSize = "12px";
    sub.style.marginBottom = "16px";
    sub.textContent = "Management rollup for one project — every number reads live from Portfolio, Schedule, Cost Tracking, Risk Register, RFI/TQ, Change Management, and Meetings.";
    outlet.appendChild(sub);

    var toolbar = document.createElement("div");
    toolbar.className = "toolbar no-print";
    var projSelect = document.createElement("select");
    if (activeProjects.length === 0) {
      var noProjOpt = document.createElement("option");
      noProjOpt.textContent = "No projects yet — add one in Portfolio first";
      projSelect.appendChild(noProjOpt);
      projSelect.disabled = true;
    } else {
      activeProjects.forEach(function (p) {
        var opt = document.createElement("option");
        opt.value = p.id;
        opt.textContent = p.name || "(unnamed project)";
        projSelect.appendChild(opt);
      });
      if (!uiState.projectId || !activeProjects.some(function (p) { return p.id === uiState.projectId; })) {
        uiState.projectId = activeProjects[0].id;
      }
      projSelect.value = uiState.projectId;
    }
    projSelect.onchange = function () {
      uiState.projectId = projSelect.value;
      rerender();
    };
    toolbar.appendChild(projSelect);
    var spacer = document.createElement("div");
    spacer.className = "toolbar__spacer";
    toolbar.appendChild(spacer);

    [{ key: "overview", label: "Overview" }, { key: "output", label: "Snapshot & Management Pack" }].forEach(function (t) {
      var btn = document.createElement("button");
      btn.className = "btn " + (uiState.tab === t.key ? "btn--primary" : "btn--ghost");
      btn.textContent = t.label;
      btn.onclick = function () { uiState.tab = t.key; rerender(); };
      toolbar.appendChild(btn);
    });
    outlet.appendChild(toolbar);

    if (activeProjects.length === 0) {
      var empty = document.createElement("div");
      empty.className = "panel empty-state";
      empty.textContent = "Add a project in Portfolio first to see its Executive Center.";
      outlet.appendChild(empty);
      return;
    }

    var ctx = buildProjectContext(data, uiState.projectId);
    var health = window.PCC.projectHealthEngine.computeHealthScore(healthContextFrom(ctx), data.settings.health_score_weights);
    var diagnostics = window.PCC.projectHealthEngine.computeDiagnostics(diagnosticsContextFrom(ctx));

    if (uiState.tab === "overview") {
      renderOverviewTab(outlet, data, ctx, health, diagnostics, rerender);
    } else {
      renderOutputTab(outlet, data, ctx, health, diagnostics, rerender);
    }
  }

  // ---------------------------------------------------------------------------------
  // Overview tab
  // ---------------------------------------------------------------------------------

  var RAG_LABELS = { on_track: "On Track", at_risk: "At Risk", critical: "Critical", unknown: "Not Yet Scored" };
  var RAG_COLOR_VAR = { on_track: "--status-on-track", at_risk: "--status-at-risk", critical: "--status-critical", unknown: "--text-secondary" };

  function ragBadge(rag) {
    var span = document.createElement("span");
    span.className = "status-badge status-badge--" + (rag === "on_track" ? "on_track" : rag === "at_risk" ? "at_risk" : rag === "critical" ? "critical" : "info");
    span.textContent = RAG_LABELS[rag] || rag;
    return span;
  }

  function renderOverviewTab(outlet, data, ctx, health, diagnostics, rerender) {
    var p = ctx.project;

    // ---- Project Overview panel ----
    var overviewPanel = document.createElement("div");
    overviewPanel.className = "panel";
    var ovHeader = document.createElement("div");
    ovHeader.style.display = "flex";
    ovHeader.style.justifyContent = "space-between";
    ovHeader.style.alignItems = "flex-start";
    ovHeader.style.marginBottom = "12px";
    var ovTitle = document.createElement("div");
    ovTitle.innerHTML = "<h3 style='margin-bottom:2px;'>" + esc(p.name || "(unnamed project)") + "</h3>" +
      "<span class='text-secondary' style='font-size:12px;'>" + esc(p.client || "—") + (p.sector ? " · " + esc(p.sector) : "") + (p.project_type ? " · " + esc(p.project_type) : "") + "</span>";
    ovHeader.appendChild(ovTitle);
    ovHeader.appendChild(ragBadge(health.rag));
    overviewPanel.appendChild(ovHeader);

    var grid = document.createElement("div");
    grid.className = "detail-grid";
    function ovItem(label, value) {
      var div = document.createElement("div");
      div.innerHTML = "<span class='detail-item__label'>" + esc(label) + "</span><div>" + (value === null || value === undefined || value === "" ? "—" : esc(value)) + "</div>";
      grid.appendChild(div);
    }
    ovItem("Location", [p.location, p.country].filter(Boolean).join(", "));
    ovItem("Current Phase", p.current_phase);
    ovItem("Contract Value", fmtMoney(p.contract_value, p.currency));
    ovItem("Budget", fmtMoney(ctx.costSummary.budgeted, p.currency) + (ctx.costSummary.usingPortfolioBudget ? " (from Portfolio field)" : ""));
    ovItem("Actual Cost", fmtMoney(ctx.costSummary.actual, p.currency));
    ovItem("Start Date", ctx.plannedStart);
    ovItem("Planned Finish", ctx.plannedFinish);
    ovItem(
      "Forecast Finish",
      ctx.forecastFinish ? ctx.forecastFinish + (ctx.forecastFinishSource === "calculated" ? " (calculated)" : " (manual)") : null
    );
    ovItem("Data Date", ctx.schedule ? ctx.schedule.data_date : null);
    ovItem("Project Manager", p.project_manager);
    ovItem("Planner", p.planner);
    ovItem("Overall Progress", fmtPct(p.progress));
    overviewPanel.appendChild(grid);
    outlet.appendChild(overviewPanel);

    // ---- KPI cards ----
    renderKpiSection(outlet, "PROGRESS", [
      { label: "Overall Progress", value: fmtPct(p.progress) },
      { label: "Schedule Progress", value: fmtPct(ctx.scheduleProgressPct) },
      { label: "Physical Progress", value: fmtPct(ctx.physicalProgressPct) },
    ]);

    if (ctx.totalActivityCount > 0) {
      renderKpiSection(outlet, "SCHEDULE", [
        { label: "Critical Activities", value: ctx.criticalActivities.length, colorVar: ctx.criticalActivities.length ? "--status-critical" : null },
        { label: "Near-Critical", value: ctx.nearCriticalActivities.length, colorVar: ctx.nearCriticalActivities.length ? "--status-at-risk" : null },
        { label: "Delayed Activities", value: ctx.delayedActivities.length, colorVar: ctx.delayedActivities.length ? "--status-critical" : null },
        { label: "Upcoming Milestones", value: ctx.upcomingMilestones.length },
        {
          label: "Schedule Variance",
          value: ctx.forecastVarianceDays == null ? "—" : (ctx.forecastVarianceDays > 0 ? "+" : "") + ctx.forecastVarianceDays + "d",
          colorVar: ctx.forecastVarianceDays > 0 ? "--status-critical" : null,
        },
      ]);
    } else {
      renderKpiEmptySection(outlet, "SCHEDULE", "No schedule with activities yet — see the Schedule page.");
    }

    renderKpiSection(outlet, "COST", [
      { label: "Budget", value: fmtMoney(ctx.costSummary.budgeted, p.currency) },
      { label: "Actual", value: fmtMoney(ctx.costSummary.actual, p.currency) },
      { label: "Variance", value: fmtMoney(ctx.costSummary.variance, p.currency), colorVar: ctx.costSummary.variance < 0 ? "--status-critical" : "--status-on-track" },
    ], "Commitments and Cash Flow aren't tracked anywhere in PCC yet, so they're left off rather than shown as an always-empty tile.");

    if (ctx.evm) {
      renderKpiSection(outlet, "EVM" + (ctx.evm.coveragePct != null && ctx.evm.coveragePct < 100 ? " (" + ctx.evm.coveragePct + "% of budget linked to schedule)" : ""), [
        { label: "PV", value: fmtMoney(ctx.evm.pv, p.currency) },
        { label: "EV", value: fmtMoney(ctx.evm.ev, p.currency) },
        { label: "AC", value: fmtMoney(ctx.evm.ac, p.currency) },
        { label: "SPI", value: ctx.evm.spi == null ? "—" : ctx.evm.spi.toFixed(2), colorVar: ctx.evm.spi != null && ctx.evm.spi < 1 ? "--status-critical" : null },
        { label: "CPI", value: ctx.evm.cpi == null ? "—" : ctx.evm.cpi.toFixed(2), colorVar: ctx.evm.cpi != null && ctx.evm.cpi < 1 ? "--status-critical" : null },
        { label: "BAC", value: fmtMoney(ctx.evm.bac, p.currency) },
        { label: "EAC", value: fmtMoney(ctx.evm.eac, p.currency) },
        { label: "ETC", value: fmtMoney(ctx.evm.etc, p.currency) },
        { label: "VAC", value: fmtMoney(ctx.evm.vac, p.currency), colorVar: ctx.evm.vac != null && ctx.evm.vac < 0 ? "--status-critical" : null },
      ]);
    }

    renderKpiSection(outlet, "RISKS", [
      { label: "Open Risks", value: ctx.openRisks.length },
      { label: "High Risks", value: ctx.highRisks.length, colorVar: ctx.highRisks.length ? "--status-critical" : null },
    ]);
    renderKpiSection(outlet, "ISSUES", [
      { label: "Open Issues", value: ctx.openIssues.length },
      { label: "Critical Issues", value: ctx.criticalIssues.length, colorVar: ctx.criticalIssues.length ? "--status-critical" : null },
    ]);
    renderKpiSection(outlet, "RFIs", [
      { label: "Open RFIs", value: ctx.openRfis.length },
      { label: "Overdue RFIs", value: ctx.overdueRfis.length, colorVar: ctx.overdueRfis.length ? "--status-critical" : null },
      { label: "Avg. Response Time", value: ctx.avgRfiResponseDays == null ? "—" : ctx.avgRfiResponseDays.toFixed(1) + "d" },
    ]);
    renderKpiSection(outlet, "CHANGES", [
      { label: "Open Change Orders", value: ctx.openChangeOrders.length },
      { label: "Pending Approvals", value: ctx.pendingChangeOrders.length, colorVar: ctx.pendingChangeOrders.length ? "--status-at-risk" : null },
      { label: "Approved", value: ctx.approvedChangeOrders.length },
    ]);

    // Gate 11: only shown once Resource Management has real data, matching the same
    // "only display when the module exists" rule EVM already follows.
    if (data.resources.length > 0) {
      renderKpiSection(outlet, "RESOURCES", [
        { label: "Resources Assigned", value: ctx.assignedResourceCount },
        {
          label: "Over-Allocated (Portfolio-Wide)",
          value: ctx.overAllocatedResources.length,
          colorVar: ctx.overAllocatedResources.length ? "--status-critical" : null,
        },
      ]);
    }

    // ---- Health Score ----
    outlet.appendChild(renderHealthScorePanel(health, data, rerender));

    // ---- Diagnostics / Alerts ----
    outlet.appendChild(renderDiagnosticsPanel(diagnostics));

    // ---- Executive Summary ----
    outlet.appendChild(renderExecutiveSummaryPanel(data, ctx, rerender));

    // ---- Charts ----
    outlet.appendChild(renderChartsSection(ctx));

    // ---- Recent Activity / Upcoming / Management Actions ----
    var threeCol = document.createElement("div");
    threeCol.style.display = "flex";
    threeCol.style.gap = "16px";
    threeCol.style.flexWrap = "wrap";
    threeCol.style.marginTop = "16px";
    threeCol.appendChild(renderRecentActivityPanel(ctx));
    threeCol.appendChild(renderUpcomingItemsPanel(ctx, rerender));
    outlet.appendChild(threeCol);

    outlet.appendChild(renderManagementActionListPanel(ctx));
  }

  function renderKpiSection(outlet, title, kpis, footnote) {
    var wrap = document.createElement("div");
    wrap.style.marginTop = "16px";
    var h = document.createElement("h4");
    h.style.marginBottom = "8px";
    h.style.fontSize = "12px";
    h.style.letterSpacing = "1px";
    h.className = "text-secondary";
    h.textContent = title;
    wrap.appendChild(h);
    var grid = document.createElement("div");
    grid.className = "kpi-grid";
    kpis.forEach(function (k) {
      var card = document.createElement("div");
      card.className = "kpi-card";
      var valueStyle = k.colorVar ? ' style="color:var(' + k.colorVar + ')"' : "";
      card.innerHTML = '<span class="kpi-card__label">' + esc(k.label) + '</span><span class="kpi-card__value mono"' + valueStyle + ">" + esc(k.value) + "</span>";
      grid.appendChild(card);
    });
    wrap.appendChild(grid);
    if (footnote) {
      var note = document.createElement("p");
      note.className = "text-secondary";
      note.style.fontSize = "11px";
      note.style.marginTop = "-6px";
      note.textContent = footnote;
      wrap.appendChild(note);
    }
    outlet.appendChild(wrap);
  }

  function renderKpiEmptySection(outlet, title, message) {
    var wrap = document.createElement("div");
    wrap.style.marginTop = "16px";
    var h = document.createElement("h4");
    h.style.marginBottom = "8px";
    h.style.fontSize = "12px";
    h.style.letterSpacing = "1px";
    h.className = "text-secondary";
    h.textContent = title;
    wrap.appendChild(h);
    var panel = document.createElement("div");
    panel.className = "panel empty-state";
    panel.textContent = message;
    wrap.appendChild(panel);
    outlet.appendChild(wrap);
  }

  // ---------------------------------------------------------------------------------
  // Health Score panel — gauge + configurable weights + full breakdown, per the spec's
  // explicit "don't hide the underlying logic" requirement.
  // ---------------------------------------------------------------------------------

  function healthGaugeSvg(score, rag) {
    var size = 160;
    var r = 64;
    var cx = size / 2;
    var cy = size / 2 + 10;
    var circumference = Math.PI * r; // half circle
    var svg = svgEl("svg", { width: size, height: size / 2 + 30, viewBox: "0 0 " + size + " " + (size / 2 + 30) });
    svg.appendChild(
      svgEl("path", {
        d: "M " + (cx - r) + " " + cy + " A " + r + " " + r + " 0 0 1 " + (cx + r) + " " + cy,
        fill: "none", stroke: "var(--divider)", "stroke-width": 16, "stroke-linecap": "round",
      })
    );
    if (score != null) {
      var frac = score / 100;
      var dash = frac * circumference;
      svg.appendChild(
        svgEl("path", {
          d: "M " + (cx - r) + " " + cy + " A " + r + " " + r + " 0 0 1 " + (cx + r) + " " + cy,
          fill: "none", stroke: "var(" + RAG_COLOR_VAR[rag] + ")", "stroke-width": 16, "stroke-linecap": "round",
          "stroke-dasharray": dash + " " + (circumference - dash),
        })
      );
    }
    var text = svgEl("text", { x: cx, y: cy - 6, "font-size": 28, "font-weight": "700", "text-anchor": "middle", fill: "var(--text-primary)" });
    text.textContent = score == null ? "—" : String(score);
    svg.appendChild(text);
    return svg;
  }

  function renderHealthScorePanel(health, data, rerender) {
    var panel = document.createElement("div");
    panel.className = "panel";
    panel.style.marginTop = "16px";
    var header = document.createElement("div");
    header.style.display = "flex";
    header.style.justifyContent = "space-between";
    header.style.alignItems = "center";
    var h = document.createElement("h3");
    h.textContent = "Project Health Score";
    header.appendChild(h);
    var configureBtn = document.createElement("button");
    configureBtn.className = "btn btn--ghost no-print";
    configureBtn.textContent = uiState.editingWeights ? "Done" : "Configure Weights";
    configureBtn.onclick = function () {
      uiState.editingWeights = !uiState.editingWeights;
      rerender();
    };
    header.appendChild(configureBtn);
    panel.appendChild(header);

    var body = document.createElement("div");
    body.style.display = "flex";
    body.style.gap = "24px";
    body.style.flexWrap = "wrap";
    body.style.alignItems = "flex-start";

    var gaugeWrap = document.createElement("div");
    gaugeWrap.style.textAlign = "center";
    gaugeWrap.appendChild(healthGaugeSvg(health.score, health.rag));
    var ragLine = document.createElement("div");
    ragLine.appendChild(ragBadge(health.rag));
    gaugeWrap.appendChild(ragLine);
    body.appendChild(gaugeWrap);

    var breakdownWrap = document.createElement("div");
    breakdownWrap.style.flex = "1 1 320px";
    var table = document.createElement("table");
    table.style.width = "100%";
    table.style.fontSize = "12px";
    table.style.borderCollapse = "collapse";
    var thead = document.createElement("tr");
    ["Factor", "Weight", "Score", "Contribution", "Why"].forEach(function (h2) {
      var th = document.createElement("th");
      th.textContent = h2;
      th.style.textAlign = "left";
      th.style.borderBottom = "1px solid var(--divider)";
      th.style.padding = "4px 6px";
      thead.appendChild(th);
    });
    table.appendChild(thead);

    health.breakdown.forEach(function (f) {
      var tr = document.createElement("tr");
      function td(text) {
        var cell = document.createElement("td");
        cell.style.padding = "4px 6px";
        cell.style.borderBottom = "1px solid var(--divider)";
        cell.style.verticalAlign = "top";
        cell.textContent = text;
        return cell;
      }
      tr.appendChild(td(f.label));
      if (uiState.editingWeights) {
        var weightCell = document.createElement("td");
        weightCell.style.padding = "4px 6px";
        weightCell.style.borderBottom = "1px solid var(--divider)";
        var input = document.createElement("input");
        input.type = "number";
        input.min = "0";
        input.style.width = "56px";
        input.value = f.weight;
        input.onchange = function () {
          window.PCC.store.update(function (d) {
            d.settings.health_score_weights[f.key] = Number(input.value) || 0;
          });
          rerender();
        };
        weightCell.appendChild(input);
        tr.appendChild(weightCell);
      } else {
        tr.appendChild(td(f.weight + (f.weightPct ? " (" + f.weightPct.toFixed(0) + "% used)" : "")));
      }
      tr.appendChild(td(f.available ? f.score.toFixed(0) : "n/a"));
      tr.appendChild(td(f.available ? f.contribution.toFixed(1) : "—"));
      tr.appendChild(td(f.note));
      table.appendChild(tr);
    });
    breakdownWrap.appendChild(table);
    var note = document.createElement("p");
    note.className = "text-secondary";
    note.style.fontSize = "11px";
    note.style.marginTop = "8px";
    note.textContent =
      "Score = weighted average of each available factor's 0–100 sub-score (weights re-normalized over just the factors with real data — a project with no budget set yet doesn't get penalized for a missing Cost factor). Edit weights above; they apply to every project.";
    breakdownWrap.appendChild(note);
    body.appendChild(breakdownWrap);

    panel.appendChild(body);
    return panel;
  }

  var SEVERITY_BADGE_CLASS = { critical: "status-badge--critical", warning: "status-badge--at_risk", info: "status-badge--info" };
  var SEVERITY_LABEL = { critical: "Critical", warning: "Warning", info: "Info" };

  function renderDiagnosticsPanel(diagnostics) {
    var panel = document.createElement("div");
    panel.className = "panel";
    panel.style.marginTop = "16px";
    var h = document.createElement("h3");
    h.style.marginBottom = "10px";
    h.textContent = "Project Health Diagnostics (" + diagnostics.length + ")";
    panel.appendChild(h);
    if (diagnostics.length === 0) {
      var okP = document.createElement("p");
      okP.className = "text-secondary";
      okP.style.fontSize = "13px";
      okP.textContent = "No rule-based alerts right now.";
      panel.appendChild(okP);
      return panel;
    }
    var list = document.createElement("div");
    list.className = "project-list";
    diagnostics.forEach(function (a) {
      var row = document.createElement("div");
      row.className = "detail-card";
      row.style.display = "flex";
      row.style.justifyContent = "space-between";
      row.style.alignItems = "center";
      row.style.gap = "10px";
      row.style.marginBottom = "6px";
      var main = document.createElement("div");
      main.innerHTML =
        "<span class='status-badge " + SEVERITY_BADGE_CLASS[a.severity] + "'>" + SEVERITY_LABEL[a.severity] + "</span> " +
        "<span class='text-secondary' style='font-size:11px;'>" + esc(a.source) + "</span><br/>" +
        "<span style='font-size:13px;'>" + esc(a.description) + "</span>";
      row.appendChild(main);
      if (a.link && a.link.module) {
        var linkBtn = document.createElement("button");
        linkBtn.className = "btn btn--ghost no-print";
        linkBtn.textContent = "View";
        linkBtn.onclick = function () { navigateToLink(a.link); };
        row.appendChild(linkBtn);
      }
      list.appendChild(row);
    });
    panel.appendChild(list);
    return panel;
  }

  /** Central place every "View" / management-action link goes through, since the same
   * cross-page navigation pattern (set the target page's own filter state, then
   * router.go) is already used throughout this app (Portfolio's Details panel,
   * Meetings' hub links). */
  function navigateToLink(link) {
    if (!link || !link.module) return;
    if (link.module === "risks" && window.PCC.risks) {
      if (link.recordId && window.PCC.risks.expandRisk) window.PCC.risks.expandRisk(link.recordId);
    } else if (link.module === "rfis" && window.PCC.rfis) {
      if (link.recordId && window.PCC.rfis.expandRfi) window.PCC.rfis.expandRfi(link.recordId);
    } else if (link.module === "meetings" && window.PCC.meetings) {
      if (link.recordId && window.PCC.meetings.expandMeeting) window.PCC.meetings.expandMeeting(link.recordId);
    } else if (link.module === "changeOrders" && window.PCC.changeOrders) {
      if (uiState.projectId && window.PCC.changeOrders.filterByProject) window.PCC.changeOrders.filterByProject(uiState.projectId);
    } else if (link.module === "cost" && window.PCC.cost) {
      // cost.js's filterByProject() always lands on its Budget tab (no public API to
      // pick EVM/Summary directly) — acceptable here since the project filter still
      // gets the user to the right place; they switch tabs themselves from there.
      window.PCC.cost.filterByProject(uiState.projectId);
    }
    window.PCC.router.go(link.module);
  }

  // ---------------------------------------------------------------------------------
  // Executive Summary — template/data-driven, never AI-generated. Each section shows
  // its computed default text unless the user has edited and saved an override (stored
  // in data.executive_summaries, one record per project — see store.js).
  // ---------------------------------------------------------------------------------

  var SUMMARY_SECTIONS = [
    { key: "status", label: "Project Status", overrideKey: "status_override", auto: autoStatusText },
    { key: "achievements", label: "Achievements", overrideKey: "achievements_override", auto: autoAchievementsText },
    { key: "challenges", label: "Challenges", overrideKey: "challenges_override", auto: autoChallengesText },
    { key: "attention", label: "Management Attention", overrideKey: "management_attention_override", auto: autoAttentionText },
    { key: "upcoming", label: "Upcoming", overrideKey: "upcoming_override", auto: autoUpcomingText },
    { key: "documentControl", label: "Document Control Status", overrideKey: "document_control_override", auto: autoDocumentControlText },
  ];

  function autoStatusText(ctx) {
    var p = ctx.project;
    var lines = [];
    lines.push((p.name || "This project") + " is currently " + (p.status || "on_track").replace("_", " ") + ", " + fmtPct(p.progress) + " complete overall.");
    if (ctx.totalActivityCount > 0) {
      lines.push(
        "Schedule progress is " + fmtPct(ctx.scheduleProgressPct) + " against a planned finish of " + (ctx.plannedFinish || "not set") + "." +
        (ctx.forecastFinish
          ? " Forecast finish is " + ctx.forecastFinish + (ctx.forecastVarianceDays ? " (" + (ctx.forecastVarianceDays > 0 ? "+" : "") + ctx.forecastVarianceDays + " day(s) vs plan)" : ", on plan") + "."
          : "")
      );
    }
    if (ctx.costSummary.budgeted > 0) {
      lines.push("Cost: " + fmtMoney(ctx.costSummary.actual, p.currency) + " actual against a " + fmtMoney(ctx.costSummary.budgeted, p.currency) + " budget.");
    }
    return lines.join(" ");
  }

  function autoAchievementsText(ctx) {
    var lines = [];
    var completedMilestones = ctx.activities.filter(function (a) { return a.activity_type === "milestone" && a.status === "complete"; });
    if (completedMilestones.length) {
      lines.push("Completed milestones: " + completedMilestones.map(function (a) { return a.name; }).join(", ") + ".");
    }
    var completedActivities = ctx.activities
      .filter(function (a) { return a.activity_type !== "milestone" && a.status === "complete"; })
      .sort(function (a, b) { return (b.duration || 0) - (a.duration || 0); })
      .slice(0, 5);
    if (completedActivities.length) {
      lines.push("Completed activities: " + completedActivities.map(function (a) { return a.name; }).join(", ") + ".");
    }
    if (lines.length === 0) return "No completed milestones or activities recorded yet.";
    return lines.join(" ");
  }

  function autoChallengesText(ctx) {
    var lines = [];
    if (ctx.delayedActivities.length) lines.push(ctx.delayedActivities.length + " activity(ies) currently delayed.");
    if (ctx.highRisks.length) lines.push(ctx.highRisks.length + " open high-severity risk(s): " + ctx.highRisks.map(function (r) { return r.title; }).join(", ") + ".");
    if (ctx.openIssues.length) lines.push(ctx.openIssues.length + " open issue(s).");
    if (lines.length === 0) return "No significant delays, high risks, or open issues at this time.";
    return lines.join(" ");
  }

  function autoAttentionText(ctx) {
    var lines = [];
    if (ctx.pendingChangeOrders.length) lines.push(ctx.pendingChangeOrders.length + " Change Order(s) awaiting a decision.");
    if (ctx.overdueRfis.length) lines.push(ctx.overdueRfis.length + " overdue RFI/TQ requiring response.");
    if (ctx.highRisks.length) lines.push(ctx.highRisks.length + " high-severity risk(s) needing a mitigation decision.");
    if (lines.length === 0) return "Nothing currently requires management decision or approval.";
    return lines.join(" ");
  }

  function autoUpcomingText(ctx) {
    var lines = [];
    if (ctx.upcomingMilestones.length) {
      lines.push("Upcoming milestones: " + ctx.upcomingMilestones.slice(0, 5).map(function (m) { return m.name + " (" + m.date + ")"; }).join(", ") + ".");
    }
    if (ctx.criticalActivities.length) lines.push(ctx.criticalActivities.length + " critical-path activity(ies) to watch.");
    if (ctx.upcomingMeetings.length) lines.push(ctx.upcomingMeetings.length + " meeting(s) scheduled.");
    if (lines.length === 0) return "No upcoming milestones, meetings, or critical activities on record.";
    return lines.join(" ");
  }

  // Gate 27 (Document Control 13: Executive Summary).
  function autoDocumentControlText(ctx) {
    if (!ctx.docControlTotal) return "No document requirements have been assigned to this project yet.";
    var lines = [];
    lines.push(ctx.docControlAvailable + " of " + ctx.docControlTotal + " required documents are Available.");
    if (ctx.docControlOverdue > 0) {
      lines.push(ctx.docControlOverdue + " overdue: " + ctx.docControlOverdueTypeNames.join(", ") + ".");
    } else {
      lines.push("Nothing is overdue.");
    }
    return lines.join(" ");
  }

  function renderExecutiveSummaryPanel(data, ctx, rerender) {
    var summaryRecord = data.executive_summaries.find(function (s) { return s.project_id === ctx.project.id; });

    var panel = document.createElement("div");
    panel.className = "panel";
    panel.style.marginTop = "16px";
    var h = document.createElement("h3");
    h.style.marginBottom = "10px";
    h.textContent = "Executive Summary";
    panel.appendChild(h);
    var note = document.createElement("p");
    note.className = "text-secondary no-print";
    note.style.fontSize = "11px";
    note.style.marginBottom = "10px";
    note.textContent = "Generated from real project data below. Edit any section to override it before printing/exporting; overrides are saved and persist until reset.";
    panel.appendChild(note);

    SUMMARY_SECTIONS.forEach(function (section) {
      var override = summaryRecord ? summaryRecord[section.overrideKey] : "";
      var autoText = section.auto(ctx);
      var displayText = override || autoText;

      var sectionWrap = document.createElement("div");
      sectionWrap.style.marginBottom = "14px";
      var sectionHeader = document.createElement("div");
      sectionHeader.style.display = "flex";
      sectionHeader.style.justifyContent = "space-between";
      sectionHeader.style.alignItems = "center";
      var label = document.createElement("strong");
      label.style.fontSize = "13px";
      label.textContent = section.label.toUpperCase() + (override ? " (edited)" : "");
      sectionHeader.appendChild(label);

      if (uiState.editingSummarySection !== section.key) {
        var editBtn = document.createElement("button");
        editBtn.className = "btn btn--ghost no-print";
        editBtn.textContent = "Edit";
        editBtn.onclick = function () {
          uiState.editingSummarySection = section.key;
          rerender();
        };
        sectionHeader.appendChild(editBtn);
      }
      sectionWrap.appendChild(sectionHeader);

      if (uiState.editingSummarySection === section.key) {
        var textarea = document.createElement("textarea");
        textarea.rows = 3;
        textarea.style.width = "100%";
        textarea.style.marginTop = "6px";
        textarea.value = displayText;
        sectionWrap.appendChild(textarea);

        var actions = document.createElement("div");
        actions.style.display = "flex";
        actions.style.gap = "8px";
        actions.style.marginTop = "6px";

        var saveBtn = document.createElement("button");
        saveBtn.className = "btn btn--primary";
        saveBtn.textContent = "Save";
        saveBtn.onclick = function () {
          window.PCC.store.update(function (d) {
            var rec = d.executive_summaries.find(function (s) { return s.project_id === ctx.project.id; });
            if (!rec) {
              rec = window.PCC.store.newExecutiveSummary({ project_id: ctx.project.id });
              d.executive_summaries.push(rec);
            }
            rec[section.overrideKey] = textarea.value;
            rec.updated_at = new Date().toISOString();
          });
          uiState.editingSummarySection = null;
          rerender();
        };
        actions.appendChild(saveBtn);

        if (override) {
          var resetBtn = document.createElement("button");
          resetBtn.className = "btn btn--ghost";
          resetBtn.textContent = "Reset to Auto-generated";
          resetBtn.onclick = function () {
            window.PCC.store.update(function (d) {
              var rec = d.executive_summaries.find(function (s) { return s.project_id === ctx.project.id; });
              if (rec) rec[section.overrideKey] = "";
            });
            uiState.editingSummarySection = null;
            rerender();
          };
          actions.appendChild(resetBtn);
        }

        var cancelBtn = document.createElement("button");
        cancelBtn.className = "btn btn--ghost";
        cancelBtn.textContent = "Cancel";
        cancelBtn.onclick = function () {
          uiState.editingSummarySection = null;
          rerender();
        };
        actions.appendChild(cancelBtn);
        sectionWrap.appendChild(actions);
      } else {
        var textP = document.createElement("p");
        textP.style.fontSize = "13px";
        textP.style.marginTop = "4px";
        textP.textContent = displayText;
        sectionWrap.appendChild(textP);
      }

      panel.appendChild(sectionWrap);
    });

    return panel;
  }

  // ---------------------------------------------------------------------------------
  // Charts section
  // ---------------------------------------------------------------------------------

  function renderChartsSection(ctx) {
    var wrap = document.createElement("div");
    wrap.style.marginTop = "16px";
    var h = document.createElement("h3");
    h.style.marginBottom = "10px";
    h.textContent = "Charts";
    wrap.appendChild(h);

    var row1 = document.createElement("div");
    row1.style.display = "flex";
    row1.style.gap = "16px";
    row1.style.flexWrap = "wrap";

    var sCurveCard = chartCard("Progress S-Curve");
    sCurveChart(sCurveCard, ctx.activities, ctx.referenceDate, ctx.todayIso);
    row1.appendChild(sCurveCard);

    var criticalCard = chartCard("Critical vs Non-Critical Activities");
    if (ctx.totalActivityCount > 0) {
      var nonCritical = ctx.totalActivityCount - ctx.criticalActivities.length - ctx.nearCriticalActivities.length;
      donutChart(criticalCard, [
        { label: "Critical", value: ctx.criticalActivities.length, color: "var(--status-critical)" },
        { label: "Near-Critical", value: ctx.nearCriticalActivities.length, color: "var(--status-at-risk)" },
        { label: "Normal", value: Math.max(0, nonCritical), color: "var(--status-on-track)" },
      ]);
    } else {
      noDataNote(criticalCard);
    }
    row1.appendChild(criticalCard);

    var floatCard = chartCard("Float Distribution");
    horizontalBarChart(floatCard, floatDistributionBuckets(ctx.activities));
    row1.appendChild(floatCard);

    wrap.appendChild(row1);

    var row2 = document.createElement("div");
    row2.style.display = "flex";
    row2.style.gap = "16px";
    row2.style.flexWrap = "wrap";
    row2.style.marginTop = "16px";

    var milestoneCard = chartCard("Milestone Timeline");
    milestoneTimelineMini(milestoneCard, ctx.upcomingMilestones, ctx.todayIso);
    row2.appendChild(milestoneCard);

    var riskCard = chartCard("Risk Heat Map (open)");
    riskHeatMapMini(riskCard, ctx.openRisks.concat(ctx.openIssues));
    row2.appendChild(riskCard);

    var rfiCard = chartCard("RFI / TQ — Open vs Closed");
    var closedRfis = ctx.allRfis.length - ctx.openRfis.length;
    horizontalBarChart(rfiCard, [
      { label: "Open", value: ctx.openRfis.length, color: "var(--status-at-risk)" },
      { label: "Overdue", value: ctx.overdueRfis.length, color: "var(--status-critical)" },
      { label: "Closed", value: closedRfis, color: "var(--status-on-track)" },
    ]);
    row2.appendChild(rfiCard);

    wrap.appendChild(row2);

    var row3 = document.createElement("div");
    row3.style.display = "flex";
    row3.style.gap = "16px";
    row3.style.flexWrap = "wrap";
    row3.style.marginTop = "16px";

    var coCard = chartCard("Change Orders — Status");
    horizontalBarChart(coCard, [
      { label: "Pending", value: ctx.pendingChangeOrders.length, color: "var(--status-at-risk)" },
      { label: "Approved", value: ctx.approvedChangeOrders.length, color: "var(--status-on-track)" },
      { label: "Rejected", value: ctx.rejectedChangeOrders.length, color: "var(--status-critical)" },
    ]);
    row3.appendChild(coCard);

    wrap.appendChild(row3);
    return wrap;
  }

  // ---------------------------------------------------------------------------------
  // Recent Activity / Upcoming Items / Management Action List
  // ---------------------------------------------------------------------------------

  function renderRecentActivityPanel(ctx) {
    var card = chartCard("Recent Activity");
    card.style.flex = "1 1 320px";
    var items = [];
    ctx.activities.forEach(function (a) { items.push({ date: a.updated_at, text: "Activity “" + a.name + "” updated" + (a.status === "complete" ? " (completed)" : "") }); });
    ctx.allRisks.forEach(function (r) { items.push({ date: r.updated_at, text: (r.type === "risk" ? "Risk" : r.type === "issue" ? "Issue" : "Opportunity") + " “" + r.title + "” " + (r.status === "closed" ? "closed" : "logged/updated") }); });
    ctx.meetings.forEach(function (m) { items.push({ date: m.updated_at, text: "Meeting “" + (m.title || "(untitled)") + "” logged" }); });
    ctx.allRfis.forEach(function (r) { items.push({ date: r.updated_at, text: r.number + " " + (r.status === "answered" ? "answered" : r.status === "closed" ? "closed" : "submitted") }); });
    ctx.allChangeOrders.forEach(function (co) { items.push({ date: co.updated_at, text: co.number + " " + co.status }); });
    ctx.documents.forEach(function (d) { items.push({ date: d.uploaded_at, text: "Document “" + d.filename + "” uploaded" }); });
    ctx.dailyLogs.forEach(function (l) { items.push({ date: l.updated_at || l.created_at, text: "Daily Log entry for " + l.log_date }); });

    items = items.filter(function (i) { return i.date; }).sort(function (a, b) { return new Date(b.date) - new Date(a.date); }).slice(0, 12);
    if (items.length === 0) return (noDataNote(card, "No activity recorded yet."), card);
    var list = document.createElement("div");
    items.forEach(function (i) {
      var row = document.createElement("div");
      row.style.fontSize = "12px";
      row.style.marginBottom = "6px";
      row.innerHTML = "<span class='text-secondary'>" + new Date(i.date).toLocaleDateString() + "</span> — " + esc(i.text);
      list.appendChild(row);
    });
    card.appendChild(list);
    return card;
  }

  function renderUpcomingItemsPanel(ctx, rerender) {
    var card = chartCard("Upcoming Items");
    card.style.flex = "1 1 320px";

    var rangeSelect = document.createElement("select");
    rangeSelect.className = "no-print";
    [7, 14, 30, 60, 90].forEach(function (d) {
      var opt = document.createElement("option");
      opt.value = d;
      opt.textContent = "Next " + d + " days";
      rangeSelect.appendChild(opt);
    });
    rangeSelect.value = uiState.upcomingRangeDays;
    rangeSelect.style.marginBottom = "8px";
    rangeSelect.onchange = function () {
      uiState.upcomingRangeDays = Number(rangeSelect.value);
      rerender();
    };
    card.appendChild(rangeSelect);

    var cutoff = window.PCC.scheduleGanttLayout.addDays(ctx.todayIso, uiState.upcomingRangeDays);
    var items = [];
    ctx.upcomingMilestones.filter(function (m) { return m.date <= cutoff; }).forEach(function (m) { items.push({ date: m.date, text: "Milestone: " + m.name }); });
    ctx.criticalActivities.forEach(function (a) {
      var act = ctx.activities.find(function (x) { return x.id === a.id; });
      var finish = ctx.cpm && ctx.cpm.results[a.id] ? ctx.cpm.results[a.id].early_finish : act && act.planned_finish;
      if (finish && finish >= ctx.todayIso && finish <= cutoff) items.push({ date: finish, text: "Critical activity finishing: " + a.name });
    });
    ctx.upcomingMeetings.filter(function (m) { return m.meeting_date <= cutoff; }).forEach(function (m) { items.push({ date: m.meeting_date, text: "Meeting: " + (m.title || "(untitled)") }); });
    ctx.openRfis.filter(function (r) { return r.date_required && r.date_required >= ctx.todayIso && r.date_required <= cutoff; }).forEach(function (r) { items.push({ date: r.date_required, text: "RFI Due: " + r.number + " " + r.subject }); });

    items.sort(function (a, b) { return a.date < b.date ? -1 : 1; });
    if (items.length === 0) {
      noDataNote(card, "Nothing upcoming in the next " + uiState.upcomingRangeDays + " days.");
      return card;
    }
    var list = document.createElement("div");
    items.forEach(function (i) {
      var row = document.createElement("div");
      row.style.fontSize = "12px";
      row.style.marginBottom = "6px";
      row.innerHTML = "<span class='mono text-secondary'>" + i.date + "</span> — " + esc(i.text);
      list.appendChild(row);
    });
    card.appendChild(list);
    return card;
  }

  function renderManagementActionListPanel(ctx) {
    var panel = document.createElement("div");
    panel.className = "panel";
    panel.style.marginTop = "16px";
    var h = document.createElement("h3");
    h.style.marginBottom = "10px";
    h.textContent = "Management Action List";
    panel.appendChild(h);

    var items = [];
    ctx.delayedActivities.forEach(function (a) { items.push({ text: "Delayed activity: " + a.name + " (finish " + a.finish + ")", link: { module: "schedule" } }); });
    ctx.highRisks.forEach(function (r) { items.push({ text: "Critical risk: " + r.title, link: { module: "risks", recordId: r.id } }); });
    ctx.overdueRfis.forEach(function (r) { items.push({ text: "Overdue RFI: " + r.number + " " + r.subject, link: { module: "rfis", recordId: r.id } }); });
    ctx.pendingChangeOrders.forEach(function (co) { items.push({ text: "Pending approval: " + co.number + " " + co.title, link: { module: "changeOrders", recordId: co.id } }); });
    ctx.overdueMeetingActions.forEach(function (a) { items.push({ text: "Outstanding action (" + a.meetingTitle + "): " + a.description, link: { module: "meetings", recordId: a.meetingId } }); });
    ctx.criticalIssues.forEach(function (r) { items.push({ text: "Critical issue: " + r.title, link: { module: "risks", recordId: r.id } }); });
    ctx.slippedMilestones.forEach(function (m) { items.push({ text: "Schedule slippage: milestone “" + m.name + "” +" + m.varianceDays + "d", link: { module: "schedule" } }); });
    if (ctx.costSummary.actual > ctx.costSummary.budgeted && ctx.costSummary.budgeted > 0) {
      items.push({ text: "Cost warning: actual cost exceeds budget", link: { module: "cost" } });
    }

    if (items.length === 0) {
      var okP = document.createElement("p");
      okP.className = "text-secondary";
      okP.style.fontSize = "13px";
      okP.textContent = "Nothing outstanding.";
      panel.appendChild(okP);
      return panel;
    }

    var list = document.createElement("div");
    list.className = "project-list";
    items.forEach(function (i) {
      var row = document.createElement("div");
      row.className = "detail-card";
      row.style.display = "flex";
      row.style.justifyContent = "space-between";
      row.style.alignItems = "center";
      row.style.marginBottom = "6px";
      var text = document.createElement("span");
      text.style.fontSize = "13px";
      text.textContent = i.text;
      row.appendChild(text);
      var linkBtn = document.createElement("button");
      linkBtn.className = "btn btn--ghost no-print";
      linkBtn.textContent = "View";
      linkBtn.onclick = function () { navigateToLink(i.link); };
      row.appendChild(linkBtn);
      list.appendChild(row);
    });
    panel.appendChild(list);
    return panel;
  }

  // ---------------------------------------------------------------------------------
  // Output tab — Project Snapshot (fixed one-pager, A4 landscape) and Management Pack
  // (checkbox-driven, multi-section). Both reuse reports.js's established print
  // architecture (window.print(), .report-doc, @media print in styles.css) — per
  // CLAUDE.md this app deliberately never bundles a PDF/Word/Excel library; "Print /
  // Save as PDF" is the browser doing the PDF generation, not this app.
  // ---------------------------------------------------------------------------------

  function reportTable(headers, rows) {
    var t = document.createElement("table");
    var thead = document.createElement("thead");
    var trh = document.createElement("tr");
    headers.forEach(function (h) {
      var th = document.createElement("th");
      th.textContent = h;
      trh.appendChild(th);
    });
    thead.appendChild(trh);
    t.appendChild(thead);
    var tbody = document.createElement("tbody");
    rows.forEach(function (r) {
      var tr = document.createElement("tr");
      r.forEach(function (cell) {
        var td = document.createElement("td");
        td.textContent = cell;
        tr.appendChild(td);
      });
      tbody.appendChild(tr);
    });
    t.appendChild(tbody);
    return t;
  }

  function reportSection(title) {
    var section = document.createElement("div");
    section.className = "report-doc__section";
    var h = document.createElement("h3");
    h.textContent = title;
    h.style.marginBottom = "6px";
    section.appendChild(h);
    return section;
  }

  function reportEmptyNote(text) {
    var p = document.createElement("p");
    p.className = "text-secondary";
    p.style.fontSize = "12px";
    p.style.margin = "4px 0 0";
    p.textContent = text;
    return p;
  }

  /** One-page executive Project Snapshot, A4 landscape (see the `.snapshot-doc`/
   * `page: snapshot-page` rule in styles.css). Fixed content per the spec — not
   * configurable like the Management Pack below, since the point is a single
   * consistent page for weekly/client/steering-committee use. */
  function buildProjectSnapshotDoc(data, ctx, health, diagnostics) {
    var doc = document.createElement("div");
    doc.className = "report-doc snapshot-doc";

    var header = document.createElement("div");
    header.style.display = "flex";
    header.style.justifyContent = "space-between";
    header.style.marginBottom = "10px";
    header.innerHTML =
      "<div><h2 style='margin-bottom:2px'>" + esc(ctx.project.name || "(unnamed project)") + "</h2>" +
      "<p class='text-secondary' style='font-size:11px;margin:0'>Project Snapshot · " + esc(ctx.project.client || "") + " · Data Date " + esc(ctx.schedule ? ctx.schedule.data_date : "—") + " · Generated " + today() + "</p></div>" +
      "<div style='text-align:right;'><span class='status-badge status-badge--" + (health.rag === "on_track" ? "on_track" : health.rag === "at_risk" ? "at_risk" : health.rag === "critical" ? "critical" : "info") + "'>" + RAG_LABELS[health.rag] + "</span>" +
      "<div style='font-size:22px;font-weight:700;margin-top:4px;' class='mono'>" + (health.score == null ? "—" : health.score) + "</div></div>";
    doc.appendChild(header);

    var grid3 = document.createElement("div");
    grid3.style.display = "grid";
    grid3.style.gridTemplateColumns = "repeat(3, 1fr)";
    grid3.style.gap = "10px";

    var overview = reportSection("Overview");
    overview.appendChild(reportTable(["Field", "Value"], [
      ["Status", ctx.project.status || "—"],
      ["Overall Progress", fmtPct(ctx.project.progress)],
      ["Schedule Progress", fmtPct(ctx.scheduleProgressPct)],
      ["Planned Finish", ctx.plannedFinish || "—"],
      ["Forecast Finish", ctx.forecastFinish || "—"],
      ["Project Manager", ctx.project.project_manager || "—"],
    ]));
    grid3.appendChild(overview);

    var kpi = reportSection("KPI Summary");
    kpi.appendChild(reportTable(["Metric", "Value"], [
      ["Critical Activities", String(ctx.criticalActivities.length)],
      ["Delayed Activities", String(ctx.delayedActivities.length)],
      ["Budget", fmtMoney(ctx.costSummary.budgeted, ctx.project.currency)],
      ["Actual Cost", fmtMoney(ctx.costSummary.actual, ctx.project.currency)],
      ["Open Risks", String(ctx.openRisks.length + ctx.openIssues.length)],
      ["Open RFIs (overdue)", ctx.openRfis.length + " (" + ctx.overdueRfis.length + ")"],
    ]));
    grid3.appendChild(kpi);

    var milestones = reportSection("Milestones");
    if (ctx.upcomingMilestones.length === 0) milestones.appendChild(reportEmptyNote("No upcoming milestones."));
    else milestones.appendChild(reportTable(["Milestone", "Date"], ctx.upcomingMilestones.slice(0, 6).map(function (m) { return [m.name, m.date]; })));
    grid3.appendChild(milestones);

    doc.appendChild(grid3);

    var summarySection = reportSection("Executive Summary");
    var summaryRecord = data.executive_summaries.find(function (s) { return s.project_id === ctx.project.id; });
    SUMMARY_SECTIONS.forEach(function (s) {
      var text = (summaryRecord && summaryRecord[s.overrideKey]) || s.auto(ctx);
      var p = document.createElement("p");
      p.style.fontSize = "11px";
      p.style.margin = "4px 0";
      p.innerHTML = "<strong>" + s.label + ":</strong> " + esc(text);
      summarySection.appendChild(p);
    });
    doc.appendChild(summarySection);

    var actionsSection = reportSection("Management Actions");
    var actionTexts = diagnostics.slice(0, 8).map(function (a) { return [SEVERITY_LABEL[a.severity], a.source, a.description]; });
    if (actionTexts.length === 0) actionsSection.appendChild(reportEmptyNote("Nothing outstanding."));
    else actionsSection.appendChild(reportTable(["Severity", "Source", "Description"], actionTexts));
    doc.appendChild(actionsSection);

    return doc;
  }

  /** Multi-section Management Pack — one click assembles every checked section into a
   * single printable document. Sections with genuinely no underlying data are skipped
   * unless explicitly checked (per spec), in which case they render their own "no
   * data" note rather than fabricating content. */
  function buildManagementPackDoc(data, ctx, health, diagnostics, sections) {
    var doc = document.createElement("div");
    doc.className = "report-doc";

    if (sections.cover) {
      var cover = document.createElement("div");
      cover.style.marginBottom = "24px";
      cover.style.textAlign = "center";
      cover.style.paddingTop = "60px";
      cover.innerHTML =
        "<h1 style='margin-bottom:6px;'>" + esc(ctx.project.name || "(unnamed project)") + "</h1>" +
        "<p class='text-secondary'>Management Pack</p>" +
        "<p class='text-secondary' style='font-size:12px;'>" + esc(data.settings.company_name || "") + " · Generated " + today() + " · Data Date " + esc(ctx.schedule ? ctx.schedule.data_date : "—") + "</p>";
      doc.appendChild(cover);
    }

    if (sections.summary) {
      var execSection = reportSection("Executive Summary");
      var summaryRecord2 = data.executive_summaries.find(function (s) { return s.project_id === ctx.project.id; });
      SUMMARY_SECTIONS.forEach(function (s) {
        var text = (summaryRecord2 && summaryRecord2[s.overrideKey]) || s.auto(ctx);
        var p = document.createElement("p");
        p.style.fontSize = "12px";
        p.innerHTML = "<strong>" + s.label + ":</strong> " + esc(text);
        execSection.appendChild(p);
      });
      doc.appendChild(execSection);
    }

    if (sections.snapshot) {
      var snapWrap = reportSection("Project Snapshot");
      snapWrap.appendChild(buildProjectSnapshotDoc(data, ctx, health, diagnostics));
      doc.appendChild(snapWrap);
    }

    if (sections.kpis) {
      var kpiSection = reportSection("KPI Dashboard");
      kpiSection.appendChild(reportTable(["Metric", "Value"], [
        ["Overall Progress", fmtPct(ctx.project.progress)],
        ["Schedule Progress", fmtPct(ctx.scheduleProgressPct)],
        ["Physical Progress", fmtPct(ctx.physicalProgressPct)],
        ["Critical Activities", String(ctx.criticalActivities.length)],
        ["Near-Critical Activities", String(ctx.nearCriticalActivities.length)],
        ["Delayed Activities", String(ctx.delayedActivities.length)],
        ["Budget", fmtMoney(ctx.costSummary.budgeted, ctx.project.currency)],
        ["Actual Cost", fmtMoney(ctx.costSummary.actual, ctx.project.currency)],
        ["Open Risks / High", ctx.openRisks.length + " / " + ctx.highRisks.length],
        ["Open Issues / Critical", ctx.openIssues.length + " / " + ctx.criticalIssues.length],
        ["Open RFIs / Overdue", ctx.openRfis.length + " / " + ctx.overdueRfis.length],
        ["Open Change Orders / Pending", ctx.openChangeOrders.length + " / " + ctx.pendingChangeOrders.length],
        ["Health Score", health.score == null ? "—" : String(health.score) + " (" + RAG_LABELS[health.rag] + ")"],
      ]));
      doc.appendChild(kpiSection);
    }

    if (sections.progress) {
      var progressSection = reportSection("Progress Summary (S-Curve)");
      sCurveChart(progressSection, ctx.activities, ctx.referenceDate, ctx.todayIso);
      doc.appendChild(progressSection);
    }

    if (sections.schedule) {
      var scheduleSection = reportSection("Schedule Summary");
      if (ctx.totalActivityCount === 0) {
        scheduleSection.appendChild(reportEmptyNote("No schedule with activities for this project."));
      } else {
        scheduleSection.appendChild(reportTable(["Metric", "Value"], [
          ["Total Activities", String(ctx.totalActivityCount)],
          ["Completed", String(ctx.completedActivityCount)],
          ["Critical Path Activities", String(ctx.criticalActivities.length)],
          ["Forecast Finish", ctx.forecastFinish || "—"],
          ["Schedule Variance", ctx.forecastVarianceDays == null ? "—" : (ctx.forecastVarianceDays > 0 ? "+" : "") + ctx.forecastVarianceDays + " day(s)"],
        ]));
        var criticalPathSection = reportSection("Critical Path Summary");
        if (ctx.criticalActivities.length === 0) criticalPathSection.appendChild(reportEmptyNote("No activities currently on the critical path."));
        else criticalPathSection.appendChild(reportTable(["Activity"], ctx.criticalActivities.slice(0, 20).map(function (a) { return [a.name]; })));
        scheduleSection.appendChild(criticalPathSection);
      }
      doc.appendChild(scheduleSection);
    }

    if (sections.milestones) {
      var msSection = reportSection("Milestone Status");
      var allMilestones = ctx.activities.filter(function (a) { return a.activity_type === "milestone"; });
      if (allMilestones.length === 0) msSection.appendChild(reportEmptyNote("No milestones defined."));
      else {
        msSection.appendChild(
          reportTable(
            ["Milestone", "Date", "Status"],
            allMilestones.map(function (a) { return [a.name, a.planned_start || "—", ACTIVITY_STATUS_LABEL_MAP[a.status] || a.status]; })
          )
        );
      }
      doc.appendChild(msSection);
    }

    if (sections.cost) {
      var costSection = reportSection("Cost Summary");
      costSection.appendChild(reportTable(["Metric", "Value"], [
        ["Budget", fmtMoney(ctx.costSummary.budgeted, ctx.project.currency) + (ctx.costSummary.usingPortfolioBudget ? " (from Portfolio field)" : "")],
        ["Actual", fmtMoney(ctx.costSummary.actual, ctx.project.currency)],
        ["Variance", fmtMoney(ctx.costSummary.variance, ctx.project.currency)],
      ]));
      costSection.appendChild(reportEmptyNote("Commitments and Cash Flow aren't tracked anywhere in PCC yet."));
      doc.appendChild(costSection);
    }

    if (sections.evm) {
      var evmSection = reportSection("EVM Summary");
      if (!ctx.evm) {
        evmSection.appendChild(reportEmptyNote("No Cost Tracking budget items for this project — EVM not available."));
      } else {
        evmSection.appendChild(reportTable(["Metric", "Value"], [
          ["PV", fmtMoney(ctx.evm.pv, ctx.project.currency)],
          ["EV", fmtMoney(ctx.evm.ev, ctx.project.currency)],
          ["AC", fmtMoney(ctx.evm.ac, ctx.project.currency)],
          ["SPI", ctx.evm.spi == null ? "—" : ctx.evm.spi.toFixed(2)],
          ["CPI", ctx.evm.cpi == null ? "—" : ctx.evm.cpi.toFixed(2)],
          ["BAC", fmtMoney(ctx.evm.bac, ctx.project.currency)],
          ["EAC", fmtMoney(ctx.evm.eac, ctx.project.currency)],
          ["VAC", fmtMoney(ctx.evm.vac, ctx.project.currency)],
        ]));
      }
      doc.appendChild(evmSection);
    }

    if (sections.risks) {
      var riskSection = reportSection("Risk Summary");
      if (ctx.openRisks.length === 0) riskSection.appendChild(reportEmptyNote("No open risks."));
      else riskSection.appendChild(reportTable(["Title", "Severity", "Owner"], ctx.openRisks.map(function (r) { return [r.title, riskSeverity(r), r.owner || "—"]; })));
      doc.appendChild(riskSection);
    }
    if (sections.issues) {
      var issueSection = reportSection("Issue Summary");
      if (ctx.openIssues.length === 0) issueSection.appendChild(reportEmptyNote("No open issues."));
      else issueSection.appendChild(reportTable(["Title", "Severity", "Owner"], ctx.openIssues.map(function (r) { return [r.title, riskSeverity(r), r.owner || "—"]; })));
      doc.appendChild(issueSection);
    }
    if (sections.rfis) {
      var rfiSection = reportSection("RFI / TQ Summary");
      if (ctx.openRfis.length === 0) rfiSection.appendChild(reportEmptyNote("No open RFIs/TQs."));
      else rfiSection.appendChild(reportTable(["Number", "Subject", "Status"], ctx.openRfis.map(function (r) { return [r.number, r.subject, r.status]; })));
      doc.appendChild(rfiSection);
    }
    if (sections.changes) {
      var coSection = reportSection("Change Order Summary");
      if (ctx.allChangeOrders.length === 0) coSection.appendChild(reportEmptyNote("No Change Orders."));
      else coSection.appendChild(reportTable(["Number", "Title", "Status"], ctx.allChangeOrders.map(function (co) { return [co.number, co.title, co.status]; })));
      doc.appendChild(coSection);
    }
    if (sections.dailylog) {
      var dlSection = reportSection("Daily Site Log Summary");
      if (ctx.dailyLogs.length === 0) dlSection.appendChild(reportEmptyNote("No Daily Log entries."));
      else {
        var incidentCount = ctx.dailyLogs.filter(function (l) { return l.incidents && l.incidents.trim(); }).length;
        dlSection.appendChild(reportEmptyNote(ctx.dailyLogs.length + " entries logged, " + incidentCount + " with incidents noted."));
      }
      doc.appendChild(dlSection);
    }
    if (sections.meetings) {
      var meetingSection = reportSection("Meeting Action Summary");
      if (ctx.overdueMeetingActions.length === 0) meetingSection.appendChild(reportEmptyNote("No outstanding meeting actions."));
      else meetingSection.appendChild(reportTable(["Meeting", "Action", "Due"], ctx.overdueMeetingActions.map(function (a) { return [a.meetingTitle, a.description, a.dueDate]; })));
      doc.appendChild(meetingSection);
    }

    return doc;
  }

  var ACTIVITY_STATUS_LABEL_MAP = { not_started: "Not Started", in_progress: "In Progress", complete: "Complete", on_hold: "On Hold" };

  function renderOutputTab(outlet, data, ctx, health, diagnostics, rerender) {
    var toolbar = document.createElement("div");
    toolbar.className = "toolbar no-print";
    var modeSelect = document.createElement("select");
    [{ v: "snapshot", l: "Project Snapshot (1-page)" }, { v: "pack", l: "Management Pack" }].forEach(function (o) {
      var opt = document.createElement("option");
      opt.value = o.v;
      opt.textContent = o.l;
      modeSelect.appendChild(opt);
    });
    modeSelect.value = uiState.outputMode || "snapshot";
    modeSelect.onchange = function () {
      uiState.outputMode = modeSelect.value;
      rerender();
    };
    toolbar.appendChild(modeSelect);
    var spacer = document.createElement("div");
    spacer.className = "toolbar__spacer";
    toolbar.appendChild(spacer);
    var printBtn = document.createElement("button");
    printBtn.className = "btn btn--primary";
    printBtn.textContent = "Print / Save as PDF";
    printBtn.onclick = function () { window.print(); };
    toolbar.appendChild(printBtn);
    outlet.appendChild(toolbar);

    var mode = uiState.outputMode || "snapshot";

    if (mode === "pack") {
      var checkboxPanel = document.createElement("div");
      checkboxPanel.className = "panel no-print";
      checkboxPanel.style.marginBottom = "16px";
      var cbHeading = document.createElement("h4");
      cbHeading.style.marginBottom = "8px";
      cbHeading.textContent = "Sections to include";
      checkboxPanel.appendChild(cbHeading);
      var cbGrid = document.createElement("div");
      cbGrid.style.display = "grid";
      cbGrid.style.gridTemplateColumns = "repeat(auto-fill, minmax(180px, 1fr))";
      cbGrid.style.gap = "6px";
      var sectionLabels = {
        cover: "Cover Page", summary: "Executive Summary", snapshot: "Project Snapshot", kpis: "KPI Dashboard",
        progress: "Progress Summary (S-Curve)", schedule: "Schedule Summary", milestones: "Milestone Status",
        cost: "Cost Summary", evm: "EVM Summary", risks: "Risk Summary", issues: "Issue Summary",
        rfis: "RFI Summary", changes: "Change Summary", dailylog: "Daily Site Log Summary", meetings: "Meeting Action Summary",
      };
      Object.keys(sectionLabels).forEach(function (key) {
        var label = document.createElement("label");
        label.style.display = "flex";
        label.style.alignItems = "center";
        label.style.gap = "6px";
        label.style.fontSize = "12px";
        var cb = document.createElement("input");
        cb.type = "checkbox";
        cb.checked = uiState.packSections[key];
        cb.onchange = function () {
          uiState.packSections[key] = cb.checked;
          rerender();
        };
        label.appendChild(cb);
        label.appendChild(document.createTextNode(sectionLabels[key]));
        cbGrid.appendChild(label);
      });
      checkboxPanel.appendChild(cbGrid);
      outlet.appendChild(checkboxPanel);
    }

    var docWrap = document.createElement("div");
    docWrap.className = "panel";
    if (mode === "snapshot") {
      docWrap.appendChild(buildProjectSnapshotDoc(data, ctx, health, diagnostics));
    } else {
      docWrap.appendChild(buildManagementPackDoc(data, ctx, health, diagnostics, uiState.packSections));
    }
    outlet.appendChild(docWrap);
  }
})();

